# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'image_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SubWindow(object):
    def setupUi(self, SubWindow):
        SubWindow.setObjectName("SubWindow")
        SubWindow.resize(581, 393)
        self.centralwidget = QtWidgets.QWidget(SubWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.bl_label = QtWidgets.QLabel(self.centralwidget)
        self.bl_label.setObjectName("bl_label")
        self.gridLayout.addWidget(self.bl_label, 0, 0, 1, 1)
        self.blend_slider = QtWidgets.QSlider(self.centralwidget)
        self.blend_slider.setEnabled(True)
        self.blend_slider.setOrientation(QtCore.Qt.Horizontal)
        self.blend_slider.setObjectName("blend_slider")
        self.gridLayout.addWidget(self.blend_slider, 0, 1, 1, 1)
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setObjectName("photo")
        self.gridLayout.addWidget(self.photo, 1, 0, 1, 2)
        SubWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SubWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 581, 24))
        self.menubar.setObjectName("menubar")
        SubWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SubWindow)
        self.statusbar.setObjectName("statusbar")
        SubWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SubWindow)
        QtCore.QMetaObject.connectSlotsByName(SubWindow)

    def retranslateUi(self, SubWindow):
        _translate = QtCore.QCoreApplication.translate
        SubWindow.setWindowTitle(_translate("SubWindow", "image and trackbar"))
        self.bl_label.setText(_translate("SubWindow", "Blend: value"))
        self.photo.setText(_translate("SubWindow", "your image here"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SubWindow = QtWidgets.QMainWindow()
    ui = Ui_SubWindow()
    ui.setupUi(SubWindow)
    SubWindow.show()
    sys.exit(app.exec_())
